-- QuickShop Analytics - MySQL Database Schema (Fixed to match CSV files)
-- This schema matches the columns generated by generate_dataset.py

-- Drop existing tables if they exist
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS promotions;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS local_shops;

-- 1. Local Shops Table
CREATE TABLE local_shops (
    shop_id INT PRIMARY KEY,
    shop_name VARCHAR(100) NOT NULL,
    shop_type VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    district VARCHAR(50) NOT NULL,
    partnership_start_date DATETIME NOT NULL,
    commission_rate DECIMAL(4,2) NOT NULL,
    avg_preparation_time_minutes INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    INDEX idx_city (city),
    INDEX idx_shop_type (shop_type),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Products Table
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    subcategory VARCHAR(50) NOT NULL,
    base_price DECIMAL(10,2) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    INDEX idx_category (category),
    INDEX idx_subcategory (subcategory)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Customers Table
CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    registration_date DATETIME NOT NULL,
    city VARCHAR(50) NOT NULL,
    customer_segment VARCHAR(20) NOT NULL,
    total_orders INT DEFAULT 0,
    total_spent DECIMAL(10,2) DEFAULT 0.00,
    last_order_date DATETIME,
    INDEX idx_registration_date (registration_date),
    INDEX idx_city (city),
    INDEX idx_segment (customer_segment),
    INDEX idx_last_order (last_order_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Promotions Table
CREATE TABLE promotions (
    promotion_id INT PRIMARY KEY,
    promotion_name VARCHAR(100) NOT NULL,
    promotion_type VARCHAR(50) NOT NULL,
    discount_value DECIMAL(10,2) NOT NULL,
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    min_order_value DECIMAL(10,2) DEFAULT 0.00,
    total_uses INT DEFAULT 0,
    total_revenue_impact DECIMAL(12,2) DEFAULT 0.00,
    INDEX idx_dates (start_date, end_date),
    INDEX idx_type (promotion_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Orders Table
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    shop_id INT NOT NULL,
    order_date DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    discount DECIMAL(10,2) DEFAULT 0.00,
    delivery_fee DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    INDEX idx_customer (customer_id),
    INDEX idx_shop (shop_id),
    INDEX idx_order_date (order_date),
    INDEX idx_status (status),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (shop_id) REFERENCES local_shops(shop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Order Items Table
CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total_price DECIMAL(10,2) NOT NULL,
    INDEX idx_order (order_id),
    INDEX idx_product (product_id),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Deliveries Table
CREATE TABLE deliveries (
    delivery_id INT PRIMARY KEY,
    order_id INT NOT NULL UNIQUE,
    preparation_time_minutes INT NOT NULL,
    delivery_time_minutes INT NOT NULL,
    total_time_minutes INT NOT NULL,
    delivery_rating DECIMAL(2,1),
    INDEX idx_order (order_id),
    INDEX idx_rating (delivery_rating),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Inventory Table
CREATE TABLE inventory (
    inventory_id INT PRIMARY KEY,
    shop_id INT NOT NULL,
    product_id INT NOT NULL,
    stock_level INT NOT NULL,
    reorder_point INT NOT NULL,
    last_restocked DATETIME NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    INDEX idx_shop (shop_id),
    INDEX idx_product (product_id),
    INDEX idx_available (is_available),
    FOREIGN KEY (shop_id) REFERENCES local_shops(shop_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create Views for Common Analytics Queries

-- Daily Metrics View
CREATE OR REPLACE VIEW daily_metrics AS
SELECT 
    DATE(order_date) as date,
    COUNT(*) as total_orders,
    COUNT(DISTINCT customer_id) as unique_customers,
    SUM(CASE WHEN status = 'Delivered' THEN total_amount ELSE 0 END) as gmv,
    AVG(CASE WHEN status = 'Delivered' THEN total_amount ELSE NULL END) as avg_order_value,
    SUM(CASE WHEN status = 'Delivered' THEN 1 ELSE 0 END) as delivered_orders,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) as cancelled_orders
FROM orders
GROUP BY DATE(order_date)
ORDER BY date DESC;

-- Shop Performance View
CREATE OR REPLACE VIEW shop_performance AS
SELECT 
    s.shop_id,
    s.shop_name,
    s.shop_type,
    s.city,
    COUNT(o.order_id) as total_orders,
    SUM(CASE WHEN o.status = 'Delivered' THEN o.total_amount ELSE 0 END) as total_revenue,
    AVG(CASE WHEN o.status = 'Delivered' THEN o.total_amount ELSE NULL END) as avg_order_value,
    AVG(d.delivery_rating) as avg_rating,
    AVG(d.total_time_minutes) as avg_delivery_time,
    COUNT(DISTINCT o.customer_id) as unique_customers
FROM local_shops s
LEFT JOIN orders o ON s.shop_id = o.shop_id
LEFT JOIN deliveries d ON o.order_id = d.order_id
GROUP BY s.shop_id, s.shop_name, s.shop_type, s.city;

-- Customer Segments Summary View
CREATE OR REPLACE VIEW customer_segments_summary AS
SELECT 
    customer_segment,
    COUNT(*) as customer_count,
    AVG(total_orders) as avg_orders_per_customer,
    AVG(total_spent) as avg_lifetime_value,
    SUM(total_spent) as total_segment_revenue
FROM customers
GROUP BY customer_segment;

-- Product Performance View
CREATE OR REPLACE VIEW product_performance AS
SELECT 
    p.product_id,
    p.product_name,
    p.category,
    p.subcategory,
    COUNT(oi.order_item_id) as times_ordered,
    SUM(oi.quantity) as total_quantity_sold,
    SUM(oi.total_price) as total_revenue,
    AVG(oi.unit_price) as avg_selling_price
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name, p.category, p.subcategory;

-- City Performance View
CREATE OR REPLACE VIEW city_performance AS
SELECT 
    c.city,
    COUNT(DISTINCT c.customer_id) as total_customers,
    COUNT(DISTINCT s.shop_id) as total_shops,
    COUNT(o.order_id) as total_orders,
    SUM(CASE WHEN o.status = 'Delivered' THEN o.total_amount ELSE 0 END) as total_gmv,
    AVG(CASE WHEN o.status = 'Delivered' THEN o.total_amount ELSE NULL END) as avg_order_value
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
LEFT JOIN local_shops s ON c.city = s.city
GROUP BY c.city;

-- Delivery Performance View
CREATE OR REPLACE VIEW delivery_performance AS
SELECT 
    DATE(o.order_date) as date,
    AVG(d.preparation_time_minutes) as avg_prep_time,
    AVG(d.delivery_time_minutes) as avg_delivery_time,
    AVG(d.total_time_minutes) as avg_total_time,
    AVG(d.delivery_rating) as avg_rating,
    COUNT(*) as total_deliveries
FROM deliveries d
JOIN orders o ON d.order_id = o.order_id
GROUP BY DATE(o.order_date)
ORDER BY date DESC;

-- RFM Analysis Stored Procedure
DELIMITER //
CREATE PROCEDURE calculate_rfm()
BEGIN
    -- This procedure calculates RFM scores for customer segmentation
    SELECT 
        customer_id,
        DATEDIFF(NOW(), last_order_date) as recency_days,
        total_orders as frequency,
        total_spent as monetary,
        NTILE(5) OVER (ORDER BY DATEDIFF(NOW(), last_order_date) DESC) as recency_score,
        NTILE(5) OVER (ORDER BY total_orders ASC) as frequency_score,
        NTILE(5) OVER (ORDER BY total_spent ASC) as monetary_score
    FROM customers
    WHERE last_order_date IS NOT NULL
    ORDER BY monetary DESC;
END //
DELIMITER ;
